### GET tags
GET {{base_url}}/api/tags?page=2&per_page=2
Accept: application/json
Authorization: Bearer {{auth_token}}

### GET tag
GET {{base_url}}/api/tags/20
Accept: application/json
Authorization: Bearer {{auth_token}}

### POST tag
POST {{base_url}}/api/tags
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "tag ok",
  "description": "tag description"
}

### PUT tag
PUT {{base_url}}/api/tags/21
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "tag ok 2",
  "description": "tag description 2"
}

### DELETE tag
DELETE {{base_url}}/api/tags/20
Accept: application/json
Authorization: Bearer {{auth_token}}
